[package]
name = "halp"
version = "0.1.0"
description = "A CLI tool to get help with CLI tools"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.8", features =["derive", "env", "wrap_help"] }
dirs = "4.0.0"
serde = { version = "1.0.153", features = ["derive"] }
thiserror = "1.0.39"
toml = "0.7.2"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
panic = "unwind"
lto = true
codegen-units = 1
strip = true

[profile.bench]
opt-level = 3
debug = false
